#!/bin/bash
MYUSERNAME=OMKAR
MYPASSWORD=1025
#
y=date
STARTOFSCRIPT=$(date +%T)
ENDOFSCRIPT=$(date +%T)
#
echo " MYUSERNAME :$MYUSERNAME"
echo " MYPASSWORD : $MYPASSWORD "
echo " STARTOFSCRIPT : $STARTOFSCRIPT "
echo " ENDOFSCRIPT : $ENDOFSCRIPT "